// The classification rule and the only code that writes `.gitmodules` or the
// gitlink index. Both the sync bot and the CI validator import this so that
// "where does this repository belong" can never be answered two different ways.
//
// The rule:
//   archived             -> _archive/<name>   (update = none, never fetched)
//   active and private   -> _private/<name>
//   active and public    -> <name>
//
// Pointers are written with `git update-index --cacheinfo` rather than
// `git submodule update`. That is deliberate and load-bearing: the archived
// submodules use `update = none` and are never cloned, so there is no working
// tree to fetch into. Writing the gitlink directly is the only way to advance
// them, and it means the sync never clones 64 repositories to move 64 pointers.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

export const ARCHIVE_DIR = "_archive";
export const PRIVATE_DIR = "_private";
export const SYNC_BRANCH = "bot/sync-workspace";
export const REVIEW_LABEL = "needs-review";

// A single layout function. Everything else derives from it.
export function expectedPath(repo) {
  if (repo.archived) return `${ARCHIVE_DIR}/${repo.name}`;
  if (repo.private) return `${PRIVATE_DIR}/${repo.name}`;
  return repo.name;
}

export function expectedCloneUrl(owner, repoName) {
  return `https://github.com/${owner}/${repoName}.git`;
}

export function git(...args) {
  return execFileSync("git", ["-C", ROOT, ...args], { encoding: "utf8" });
}

export function gitIn(dir, ...args) {
  return execFileSync("git", ["-C", dir, ...args], { encoding: "utf8" });
}

// Parses `.gitmodules` through `git config` rather than a hand-rolled INI
// reader, so quoting and ordering behave exactly as git itself sees them.
export function readGitmodules() {
  const file = path.join(ROOT, ".gitmodules");
  if (!fs.existsSync(file)) return new Map();

  const entries = new Map();
  let stdout;
  try {
    stdout = git("config", "--file", ".gitmodules", "--list");
  } catch {
    return entries;
  }

  for (const line of stdout.split(/\r?\n/)) {
    const separator = line.indexOf("=");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    const match = key.match(/^submodule\.(.+)\.(path|url|branch|update)$/);
    if (!match) continue;
    const [, name, field] = match;
    if (!entries.has(name)) entries.set(name, {});
    entries.get(name)[field] = value;
  }
  return entries;
}

export function gitmodulesEntry(name, repo) {
  const entry = {
    path: expectedPath(repo),
    url: expectedCloneUrl(repo.owner, repo.name),
    branch: repo.default_branch
  };
  // Archived submodules are pinned history, not working copies. `update = none`
  // keeps them from ever being fetched on clone, which is why the pointer has to
  // be written through the index rather than through `submodule update`.
  if (repo.archived) entry.update = "none";
  return entry;
}

// Writes `.gitmodules` from scratch in the canonical grouped order. Regenerating
// rather than patching removes any chance of stale stanza keys surviving a
// rename, which is the failure that produces a repository whose gitlink exists
// with no `.gitmodules` entry for it.
export function writeGitmodules(owner, repos) {
  const ordered = [...repos].sort((a, b) => expectedPath(a).localeCompare(expectedPath(b)));

  const chunks = [
    "# Generated by .github/scripts/sync-workspace.mjs from the GitHub repository",
    "# list. Do not edit by hand: any change here is reverted on the next sync, and",
    "# the layout follows one rule -- archived goes under _archive/, active and",
    "# private under _private/, active and public at the root. Run",
    "# `node .github/scripts/sync-workspace.mjs --dry-run` to preview a regeneration."
  ];

  for (const repo of ordered) {
    const entry = gitmodulesEntry(repo.name, { ...repo, owner });
    const lines = [`[submodule "${repo.name}"]`];
    // Path first so the file reads in the same shape as the classification rule.
    for (const field of ["path", "url", "branch", "update"]) {
      if (!entry[field]) continue;
      lines.push(`\t${field} = ${entry[field]}`);
    }
    chunks.push(lines.join("\n"));
  }

  fs.writeFileSync(path.join(ROOT, ".gitmodules"), `${chunks.join("\n\n")}\n`);
}

// `.gitignore` here is a whitelist (`*` then `!` exceptions), so a new
// root-level submodule needs an exception line or git silently ignores it and the
// gitlink never stages. The file is fully generated: a single header of fixed
// entries, then one exception per active public repository, then the two
// directory wildcards which cover `_archive/*` and `_private/*` without needing
// a line per archived repository.
//
// The whole file is rewritten rather than edited in place. Locating the
// generated region inside a partially hand-edited file is exactly the kind of
// guesswork that produces an umbrella where `.gitmodules` or `.github/` silently
// stops being tracked -- which happened while this was being written.
const GITIGNORE_HEADER = [
  "# Generated by .github/scripts/sync-workspace.mjs. Do not edit by hand.",
  "#",
  "# This is a whitelist: `*` ignores everything, and each `!` below re-admits",
  "# one path. A new active public repository needs its own `!name` line here or",
  "# its submodule will not be staged. `_archive/*` and `_private/*` are",
  "# wildcarded, so archived and private repositories need no line of their own.",
  "",
  "*",
  "",
  "!.gitignore",
  "!.gitmodules",
  "!README.md",
  "!.agents/",
  "!.agents/.project/",
  "!.agents/.project/*.md",
  "!.github/",
  "!.github/scripts/",
  "!.github/scripts/*",
  "!.github/workflows/",
  "!.github/workflows/*",
  ""
];

export function writeGitignore(repos) {
  const rootPaths = repos
    .filter((repo) => !repo.archived && !repo.private)
    .map((repo) => repo.name)
    .sort();

  const block = [
    ...rootPaths.map((name) => `!${name}`),
    "",
    "!_archive",
    "!_archive/*",
    "",
    "!_private",
    "!_private/*",
    ""
  ];

  fs.writeFileSync(path.join(ROOT, ".gitignore"), [...GITIGNORE_HEADER, ...block].join("\n"));
}

export function readGitlinks() {
  const stdout = git("ls-files", "--stage");
  const links = new Map();
  for (const line of stdout.split(/\r?\n/)) {
    if (!line.startsWith("160000 ")) continue;
    const tab = line.indexOf("\t");
    links.set(line.slice(tab + 1).trim(), line.slice(41, tab).trim());
  }
  return links;
}

export function writeGitlink(repoPath, sha) {
  git("update-index", "--add", "--cacheinfo", `160000,${sha},${repoPath}`);
}

export function removeGitlink(repoPath) {
  git("update-index", "--force-remove", repoPath);
}

// Stages only the two generated text files. It must never run `git add --all`:
// that would read every submodule's on-disk HEAD and silently overwrite the
// gitlinks written by `writeGitlink`, which is exactly the value the sync exists
// to set. Gitlinks are staged exclusively through `writeGitlink`.
export function stageGeneratedFiles() {
  git("add", "--", ".gitmodules", ".gitignore");
}

// `git diff --cached` cannot be used to decide whether anything is staged. It
// skips any path whose working-tree directory does not exist, and every archived
// submodule is `update = none` and never cloned, so their directories are empty
// or absent. That made 50 correctly-updated archived pointers invisible to the
// diff and would have caused their commit to be skipped entirely. The index is
// the source of truth; compare it against HEAD directly.
export function stagedChanges() {
  return git("diff-index", "--cached", "--name-status", "HEAD").split(/\r?\n/).filter(Boolean);
}

export function hasStagedChanges() {
  const index = readGitlinks();
  const head = new Map();
  for (const line of git("ls-tree", "-r", "HEAD").split(/\r?\n/)) {
    if (!line.startsWith("160000 ")) continue;
    const tab = line.indexOf("\t");
    head.set(line.slice(tab + 1).trim(), line.slice(41, tab).trim());
  }
  for (const [path, sha] of index) {
    if (head.get(path) !== sha) return true;
  }
  return git("diff-index", "--cached", "--name-only", "HEAD", "--", ".gitmodules", ".gitignore")
    .trim() !== "";
}

export function commit(message) {
  git(
    "-c",
    "user.name=github-actions[bot]",
    "-c",
    "user.email=41898282+github-actions[bot]@users.noreply.github.com",
    "commit",
    "-m",
    message
  );
  // Clear the index so the next stage in the sync commits only its own files.
  git("reset", "--quiet");
  return git("rev-parse", "HEAD").trim();
}

// Turns the GitHub repository list into the exact state the workspace should be
// in. Both the bot and the validator consume this, which is what keeps them from
// disagreeing about what "correct" means.
export function desiredState(owner, repos, { selfName }) {
  const tracked = repos.filter((repo) => repo.name !== selfName);
  const byPath = new Map();

  for (const repo of tracked) {
    const path = expectedPath(repo);
    byPath.set(path, {
      name: repo.name,
      path,
      url: expectedCloneUrl(owner, repo.name),
      branch: repo.default_branch,
      archived: repo.archived,
      private: repo.private
    });
  }

  return { tracked, byPath };
}

// Compares desired state against what is committed. Returns every discrepancy
// in a form both callers can act on: the bot fixes them, the validator reports
// them with the expected value so a human never has to guess.
export function diffWorkspace(desired) {
  const { byPath, tracked } = desired;
  const gitmodules = readGitmodules();
  const gitlinks = readGitlinks();

  const structural = [];
  const pointerDrift = [];

  const declaredPaths = new Map();
  for (const [name, entry] of gitmodules) {
    declaredPaths.set(entry.path, { name, entry });
  }

  for (const [repoPath, want] of byPath) {
    const declared = declaredPaths.get(repoPath);
    if (!declared) {
      structural.push({ kind: "missing-submodule", repo: want.name, path: repoPath });
      continue;
    }
    const { entry } = declared;
    if (entry.url !== want.url) {
      structural.push({
        kind: "wrong-url",
        repo: want.name,
        path: repoPath,
        expected: want.url,
        actual: entry.url
      });
    }
    if (entry.branch !== want.branch) {
      structural.push({
        kind: "wrong-branch",
        repo: want.name,
        path: repoPath,
        expected: want.branch,
        actual: entry.branch
      });
    }
    const expectedUpdate = want.archived ? "none" : undefined;
    if ((entry.update ?? undefined) !== expectedUpdate) {
      structural.push({
        kind: "wrong-update-mode",
        repo: want.name,
        path: repoPath,
        expected: expectedUpdate ?? "(unset)",
        actual: entry.update ?? "(unset)"
      });
    }

    const pin = gitlinks.get(repoPath);
    if (!pin) {
      structural.push({ kind: "missing-gitlink", repo: want.name, path: repoPath });
      continue;
    }
    pointerDrift.push({ kind: "pointer", repo: want.name, path: repoPath, current: pin, want });
  }

  // Anything declared or staged but no longer backed by a repository is a
  // deletion that still needs cleaning out of the index.
  for (const [repoPath, { name }] of declaredPaths) {
    if (!byPath.has(repoPath)) {
      structural.push({ kind: "stale-submodule", repo: name, path: repoPath });
    }
  }
  for (const repoPath of gitlinks.keys()) {
    if (!byPath.has(repoPath)) {
      structural.push({ kind: "stale-gitlink", repo: repoPath.split("/").pop(), path: repoPath });
    }
  }

  return { structural, pointerDrift, tracked };
}

// Splits pointer work by whether the target repository is archived. The two
// groups are committed separately so archive churn stays isolated from the
// repositories you actively work in.
export function splitPinsByArchived(pointerDrift) {
  const activePins = [];
  const archivedPins = [];
  for (const item of pointerDrift) {
    (item.want.archived ? archivedPins : activePins).push(item);
  }
  return { activePins, archivedPins };
}